AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GraphQL:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs10.x
      Timeout: 30
      Environment:
        Variables:
          GRAPHQL_URIS: "[\"https://r12hd0umhk.execute-api.us-east-1.amazonaws.com/Prod/graphql\", \"https://c7bmvp5hr5.execute-api.us-east-1.amazonaws.com/Prod/graphql\"]"
          CORS_ORIGIN: "*"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /graphql
            Method: post
